### ISSUE TITLE
[Commands] Preferences

### ISSUE THREAD

**Issue by moruzerinho6** [TeamRizu/OutFox-Discord-Bot#20]
Command that displays all preferences documented on https://github.com/TeamRizu/outfox-wiki/blob/main/content/user-guide/config/preferences.md

PROBLEMS:

- No file to easily deal with available data (JSON), needs to either parse the page or create our own json file with the data.
- There's around 273 preferences, with a max of 25 elements per page that would mean 11 pages to a single command.

**Comment by JoseVarelaP** [comment]
We do have the Markdown data, so it could it be converted into a simple json file to avoid the overhead of scraping the website itself.

**Comment by moruzerinho6** [comment]
Fixed with [46140bc](https://github.com/TeamRizu/OutFox-Discord-Bot/commit/46140bcede5fba120985f293f486a8f908193a07)
