### ISSUE TITLE
Update customIDs separator to double -

### ISSUE THREAD

**Issue by moruzerinho6** [TeamRizu/OutFox-Discord-Bot#29]
The most recent StepMania Archive commit (https://github.com/JoseVarelaP/StepMania-Archive/commit/f53aa222aba0cb7831c788e1251d83bd273940e0) adds SM-SSC themes, the slash conflicts with Discord customIDs and makes the bot try to search themes for "SM", which will return nothing and crash the bot.

**Comment by JoseVarelaP** [comment]
oops.
I can update it so it fetches the content without a slash instead. `SMSSC`.
